manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/stephen/zmk/tree/stephen/split-encoder
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
